// Generated by CoffeeScript 2.7.0
import autoprefixer from 'autoprefixer';

import presetEnv from 'postcss-preset-env';

import colorFunction from 'postcss-color-function';

export default {
  plugins: [
    autoprefixer({}),
    presetEnv({
      stage: 1
    }),
    colorFunction({})
  ]
};
